- name: Provision Host
  hosts: all
  become: true
  vars:
      prom_server: '52.212.50.198'
      node_name_in_graf: 'localhost'
      grafana_creds:
          login: admin
          pass: admin
          url: localhost:3000

  connection: ssh
  roles:
   - docker-install
   - prometheus-server
   - prometheus-node
