- name: Creates prometeus directory
  file: path=/opt/prometheus/jmx-exporter/ state=directory

- name: download jmx-exporter
  get_url:
    url: https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.9/jmx_prometheus_javaagent-0.9.jar
    dest: /opt/prometheus/jmx-exporter/jmx_prometheus_javaagent-0.9.jar
    mode: 0666
    owner: tomcat

- template:
    src: tomcat.j2
    dest: /opt/prometheus/jmx-exporter/tomcat.yml
    mode: 666
    owner: tomcat
