- name: Creating dashboard
  uri:
      url: "http://{{ grafana_creds.url }}/api/dashboards/db/"
      method: POST
      user: "{{ grafana_creds.login }}"
      password: "{{ grafana_creds.pass }}"
      force_basic_auth: yes
      body: "{{ lookup('template', './docker_containers_in_grafana.j2') }}"
      body_format: json
      HEADER_Content-Type: "application/json"
  ignore_errors: yes
  delegate_to: "localhost"

- lineinfile:
    dest: "/etc/prometheus/prometheus.yml"
    insertafter: "#cadvisor_nodes"
    line: "      - '{{azure_hostname.stdout}}/cadvisor'"
    state: present
  delegate_to: "{{ prom_server }}"

- name: Prometheus server reload
  uri:
      url: "http://{{ prom_server }}:9090/-/reload"
      method: POST
      body: ""
      body_format: json
  ignore_errors: yes
  delegate_to: "localhost"
